
[package]
authors = ["LongYinan <lynweklm@gmail.com>"]
edition = "2021"
name = "hyperjs"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
bytes = "1.11.0"
http-body-util = "0.1.3"
hyper = { version = "1.8.1", features = ["full"] }
hyper-util = { version = "0.1.19", features = ["tokio"] }
lazy_static = "1.5.0"
napi = "3.0.0"
napi-derive = "3.0.0"
tokio = { version = "1.48.0", features = ["rt", "net", "rt-multi-thread"] }

[build-dependencies]
napi-build = "2"

[profile.release]
lto = true
strip = "symbols"
