[package]
edition = "2024"
name = "hyperjs"
version = "0.1.0"

[dependencies]
anyhow = "1.0"
axum = "0.8"
deno_core = "0.376.0"
pollster = "0.3"
reqwest = "0.12.26"
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
sqlx = {version = "0.8", features = ["runtime-tokio", "sqlite"]}
tokio = {version = "1", features = ["full"]}
tower = "0.5"
